"""initial schema

Revision ID: 80b46fc60469
Revises: 
Create Date: 2026-07-19 18:53:06.956434

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '80b46fc60469'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('side', sa.Enum('importer_eu', 'exporter_sa', name='clientside', native_enum=False, length=16), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('eori', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plot_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=43), nullable=False),
    sa.Column('source_format', sa.String(length=16), nullable=False),
    sa.Column('geometry_geojson', sa.Text(), nullable=False),
    sa.Column('geometry_type', sa.String(length=24), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('centroid_lon', sa.Float(), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('commodity', sa.Enum('cattle', 'cocoa', 'coffee', 'oil_palm', 'rubber', 'soya', 'wood', name='commodity', native_enum=False, length=16), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('risk_level', sa.Enum('green', 'amber', 'red', name='risklevel', native_enum=False, length=8), nullable=True),
    sa.Column('ruleset_version', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('dataset_versions', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plot_check', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plot_check_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_plot_check_token'), ['token'], unique=True)

    op.create_table('shipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('commodity', sa.Enum('cattle', 'cocoa', 'coffee', 'oil_palm', 'rubber', 'soya', 'wood', name='commodity', native_enum=False, length=16), nullable=True),
    sa.Column('cn_code', sa.String(length=16), nullable=True),
    sa.Column('quantity_kg', sa.Float(), nullable=True),
    sa.Column('country_of_production', sa.String(length=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'ready', 'filed', 'blocked', name='shipmentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_client_id'), ['client_id'], unique=False)

    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('commodity', sa.Enum('cattle', 'cocoa', 'coffee', 'oil_palm', 'rubber', 'soya', 'wood', name='commodity', native_enum=False, length=16), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('approx_volume_t', sa.Float(), nullable=True),
    sa.Column('magic_token', sa.String(length=64), nullable=True),
    sa.Column('outreach_status', sa.Enum('pending', 'sent', 'reminded', 'responded', 'escalated', 'failed', name='outreachstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_magic_token'), ['magic_token'], unique=True)

    op.create_table('dds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('reference_number', sa.String(length=64), nullable=True),
    sa.Column('verification_number', sa.String(length=64), nullable=True),
    sa.Column('traces_reference', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('draft', 'assembled', 'submitted', 'accepted', 'rejected', name='ddsstatus', native_enum=False, length=16), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dds_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dds_reference_number'), ['reference_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_dds_shipment_id'), ['shipment_id'], unique=False)

    op.create_table('outreach_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'reminded', 'responded', 'escalated', 'failed', name='outreachstatus', native_enum=False, length=16), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outreach_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_message_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('plot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('external_ref', sa.String(length=128), nullable=True),
    sa.Column('commodity', sa.Enum('cattle', 'cocoa', 'coffee', 'oil_palm', 'rubber', 'soya', 'wood', name='commodity', native_enum=False, length=16), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('geometry_geojson', sa.Text(), nullable=False),
    sa.Column('geometry_type', sa.String(length=24), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('centroid_lon', sa.Float(), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'valid', 'rejected', 'needs_review', name='plotstatus', native_enum=False, length=16), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Enum('green', 'amber', 'red', name='risklevel', native_enum=False, length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plot_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('glad', 'radd', 'hansen', name='alertsource', native_enum=False, length=8), nullable=False),
    sa.Column('alert_date', sa.Date(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_plot_id'), ['plot_id'], unique=False)

    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('plot_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('geometry', 'land_title', 'permit', 'certificate', 'other', name='documentkind', native_enum=False, length=16), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('extracted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plot.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_plot_id'), ['plot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('risk_level', sa.Enum('green', 'amber', 'red', name='risklevel', native_enum=False, length=8), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('dataset_versions', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_plot_id'), ['plot_id'], unique=False)

    op.create_table('shipment_plot',
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plot.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shipment_id', 'plot_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_plot')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_plot_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_document_plot_id'))

    op.drop_table('document')
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_plot_id'))

    op.drop_table('alert')
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plot_supplier_id'))

    op.drop_table('plot')
    with op.batch_alter_table('outreach_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_message_supplier_id'))

    op.drop_table('outreach_message')
    with op.batch_alter_table('dds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dds_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_dds_reference_number'))
        batch_op.drop_index(batch_op.f('ix_dds_client_id'))

    op.drop_table('dds')
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_magic_token'))
        batch_op.drop_index(batch_op.f('ix_supplier_client_id'))

    op.drop_table('supplier')
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_client_id'))

    op.drop_table('shipment')
    with op.batch_alter_table('plot_check', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plot_check_token'))
        batch_op.drop_index(batch_op.f('ix_plot_check_email'))

    op.drop_table('plot_check')
    op.drop_table('client')
    # ### end Alembic commands ###
